services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8082:8080" # Jenkins Web UI mapped to port 8082 as requested
      - "50000:50000" # JNLP Agents port
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mount the Docker socket so Jenkins can build images using the host's Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the local project directory so Jenkins can access the code without needing a remote Git server
      - ../../:/var/jenkins_home/workspace/lather-line
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home:
